CREATE DATABASE proyecto;

USE proyecto;

CREATE TABLE USUARIOS (
USUARIO_ID           INT NOT NULL AUTO_INCREMENT,
USUARIO_NOMBRE      VARCHAR(20) NOT NULL,
USUARIO_APELLIDO       VARCHAR(20) NOT NULL,
USUARIO_NICKNAME      VARCHAR(20),
USUARIO_CONTRA       VARCHAR(255) NOT NULL,
USUARIO_CORREO         VARCHAR(255) NOT NULL,
USUARIO_GENERO         CHAR(1) NOT NULL,
USUARIO_CUMPLE      DATE NOT NULL,
USUARIO_ESTADO        CHAR(1),
USUARIO_INFO         TEXT,
USUARIO_CIUDAD      VARCHAR(255),
PRIMARY KEY (USUARIO_ID)
);

CREATE TABLE AMISTAD (
USUARIO1_ID          INT NOT NULL,
USUARIO2_ID           INT NOT NULL,
ESTADO_AMISTAD   INT NOT NULL,
FOREIGN KEY (USUARIO1_ID) REFERENCES USUARIOS(USUARIO_ID),
FOREIGN KEY (USUARIO2_ID) REFERENCES USUARIOS(USUARIO_ID)
);

CREATE TABLE POSTS (
POST_ID             INT NOT NULL AUTO_INCREMENT,
POST_CONTENIDO       TEXT NOT NULL,
POST_FECHA           TIMESTAMP NOT NULL,
POST_PRIVACIDAD         CHAR(1) NOT NULL,
POST_AUTOR            INT NOT NULL,
PRIMARY KEY (POST_ID),
FOREIGN KEY (POST_AUTOR) REFERENCES USUARIOS(USUARIO_ID)
);

CREATE TABLE USUARIO_CELULAR (
USUARIO_ID         INT,
USUARIO_CELULAR     INT,
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);